version: '3.8'
services:
  # Бэкенд на Node.js (Express)
  backend:
    build: ./backend
    container_name: hash-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000" # внешний:внутренний порт
    depends_on:
      - db
    networks:
      - hashnet

  # MySQL база данных
  db:
    image: mysql:8.0
    container_name: hash-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hash_service
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - hashnet

  frontend:
    build: ./frontend
    container_name: hash-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hashnet

volumes:
  db_data:

networks:
  hashnet:

# frontend:
# db: 